### ISSUE TITLE
Missing PostAndEnsureMethodNotAllowed (405)

### ISSUE THREAD

**Issue by robertbjarum** [ardalis/HttpClientTestExtensions#38]
Can we include this? Or, is there a reason for not including this?

**Comment by ardalis** [comment]
Probably good to have if it's not already covered somewhere (on my phone so not easy to check). Submit a PR? Or someone (maybe me) should be able to knock this out quickly.

**Comment by ardalis** [comment]
Probably good to have if it's not already covered somewhere (on my phone so not easy to check). Submit a PR? Or someone (maybe me) should be able to knock this out quickly.

**Comment by ardalis** [comment]
Probably good to have if it's not already covered somewhere (on my phone so not easy to check). Submit a PR? Or someone (maybe me) should be able to knock this out quickly.

**Comment by robertbjarum** [comment]
I can submit a PR.

**Comment by ardalis** [comment]
Fixed by #39
